[project]
name = "lmhw"
version = "2025.0.0"
description = "Code accompaniying the publicationn 'Lagrangian attribution of marine heatwave drivers' with the DOI 10.1088/2515-7620/ae0f81"
readme = "README.md"
authors = [
    { name = "Ezra Eisbrenner", email = "lmhw@ezra-eisbrenner.eu" }
]
requires-python = ">=3.10,<3.13"
dependencies = []

[build-system]
requires = ["uv_build>=0.9.15,<0.10.0"]
build-backend = "uv_build"
